name: "Compile Math katex"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: kinglittleq/markdown-latex-math-render@v0.1
        with:
          markdown-files: README.md # or md_files/README.md
          output-dir: "."

      # commit changes and push
      - name: Commit
        id: git_commit
        uses: zwaldowski/git-commit-action@v1
      - run: echo "${{ steps.git_commit.outputs.sha }}"

      - run: git push origin || echo "Done!"
