name: "Compile Math katex"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: kinglittleq/markdown-latex-math-render@v0.1
        with:
          markdown-files: md_files/*.md # or md_files/README.md
          output-dir: "."

      # commit changes and push
      - name: Commit
        run: |
          git config --global user.name 'Github Action Bot'
          git config --global user.email 'bot@example.com'
          git add *.md
          git commit -m 'Render latex formulas'
          git push origin || echo "No changes to commit"
