name: render-md-mermaid

on: push

jobs:
  render-md-mermaid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Setup mdbook-mermaid
        uses: magicgh/mdbook-mermaid-action@v1
        with:
          version: "latest"

      - run: mdbook build
